name: Generate Data
on:
  schedule:
    - cron: '0 */12 * * *'   # run at minute 0 every 12 hours
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Jobs to update data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Rodrigo-Hr25
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
